// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWq8ls_F3DIA5Pkh2SYvk8j8XMH35WY-4',
    appId: '1:1008135108055:web:9bca9c071184980a388792',
    messagingSenderId: '1008135108055',
    projectId: 'pet-time-7398c',
    authDomain: 'pet-time-7398c.firebaseapp.com',
    storageBucket: 'pet-time-7398c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl5W81AKYJ4vVpqoBM7bBI5V75Byy_ZmU',
    appId: '1:1008135108055:android:e752a2b6cd17fcef388792',
    messagingSenderId: '1008135108055',
    projectId: 'pet-time-7398c',
    storageBucket: 'pet-time-7398c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJqhJUsHIakYRxNQ72Z4Rjo57Jjivgryo',
    appId: '1:1008135108055:ios:0eb35a92aa788a3f388792',
    messagingSenderId: '1008135108055',
    projectId: 'pet-time-7398c',
    storageBucket: 'pet-time-7398c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJqhJUsHIakYRxNQ72Z4Rjo57Jjivgryo',
    appId: '1:1008135108055:ios:0eb35a92aa788a3f388792',
    messagingSenderId: '1008135108055',
    projectId: 'pet-time-7398c',
    storageBucket: 'pet-time-7398c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWq8ls_F3DIA5Pkh2SYvk8j8XMH35WY-4',
    appId: '1:1008135108055:web:1c646c6628afafe6388792',
    messagingSenderId: '1008135108055',
    projectId: 'pet-time-7398c',
    authDomain: 'pet-time-7398c.firebaseapp.com',
    storageBucket: 'pet-time-7398c.firebasestorage.app',
  );

}